databases:
  - name: recipe_app
    databaseName: recipe_app_4v06
    user: recipe_app_4v06_user

services:
  - type: web
    name: recipe_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-app-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false